config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
  get "tasks/new", to: "tasks#new"
  get "tasks/:id", to: 'tasks#show', as: 'task'
  get "tasks/:id/edit", to: "tasks#edit", as: 'task_edit'
  post "tasks", to: "tasks#create"
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy"
  patch "tasks/:id/task_completed", to: "tasks#task_completed", as: 'task_completed'



  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :details, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_tasks, only: [:show, :edit, :update, :destroy, :task_completed]


  def index
    @tasks = Task.where(user: current_user)
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(tasks_params)
    @task.user = current_user



    if @task.save!
      redirect_to tasks_path, notice: "Task was successfully created."
    else
      render :new, status: :unprocessable_entity

    end
  end

  def edit
    # @task = Task.find(params[:id])
  end

  def update
    if @task.update(tasks_params)
      redirect_to task_path(@task), notice: "Task was successfully updated."
    else
      render :edit
    end
  end


  def task_completed
    @task.completed = !@task.completed
    if @task.save
      redirect_to tasks_path, notice: "Task status updated successfully."
    else
      redirect_to task_path(@task), alert: "Unable to update task status."
    end
  end

  def destroy
    # @task = Task.find(params[:id])
    @task.destroy
    # No need for app/views/restaurants/destroy.html.erb
    redirect_to tasks_path, status: :see_other
  end

  private

  def set_tasks
    @task = Task.find(params[:id])
  end



  def tasks_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://kit.fontawesome.com/c87706245d.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar">Welcome,
      <%= current_user.first_name %> <%= current_user.last_name %>!
    </a>
    <a class="navbar-brand">
      <%= link_to raw('<i class="fa-solid fa-list-check"></i> Your tasks'), tasks_path %>
    </a>
    <a class="navbar-brand">
      <%= link_to 'Logout', destroy_user_session_path, data: { "turbo-method": :delete }, class: 'nav-link' %>
    </a>
  </div>
</nav>

app/views/tasks/edit.html.erb
<%= render 'shared/navbar' %>
  <h1 class="m-4"> Edit your task</h1>
  <div class='d-flex flex-column justify-content-center'>

    <%= form_with model: @task do |f| %>
      <div class="form-group mb-2">
        <%= f.label :title %>
      </div>
      <div class="form-group mb-2">
        <%= f.text_field :title %>
      </div>
      <div class="form-group mb-2">
        <%= f.label :details %>
      </div>
      <div class="form-group mb-2">
        <%= f.text_field :details %>
      </div>
      <div class="form-group mb-2">
        <%= f.submit class:'btn btn-primary' %>
      </div>
    <% end %>
  </div>

app/views/tasks/index.html.erb
<div class="vh-100 bg-white">
  <%= render 'shared/navbar' %>
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <h1 class="text-center m-4">Task List</h1>

        <ul>
        <% if @tasks.length > 0 %>
          <% @tasks.each do |task| %>
            <li class="list-group-item mb-2">
              <%= link_to task.title, task_path(task) %>
                <% if task.completed %>
                  <i class="fa-solid fa-check"></i>
                <% end %>
            </li>
          <% end %>
          <% else %>
            <p>You don't have any tasks!</p>
          <% end %>
        </ul>
        <div class="text-center mt-3">
          <%= link_to 'Add a New Task', tasks_new_path, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
</div>

app/views/tasks/new.html.erb
<div class="d-flex flex-column">

  <%= render 'shared/navbar' %>

    <h1 class="m-4"> New task </h1>

    <div class="vw-100 justify-content-center">

      <%= form_with model: @task do |f| %>

        <div class="form-group mb-2">
          <%= f.label :title %><br/>
          <%= f.text_field :title, autofocus: true, autocomplete: "Title of the task" %>

        </div>

        <div class="form-group mb-2">
          <%= f.label :details %><br />
          <%= f.text_field :details, autofocus: true, autocomplete: "Description of the task" %>

        </div>
        <div class="actions mb-2">
          <%= f.submit "Submit Task", class: 'btn btn-primary btn-small' %>
        </div>
      <% end %>
    </div>
</div>

app/views/tasks/show.html.erb
  <%= render 'shared/navbar' %>
<div class="container mt-4">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="text-center mb-3">
        <h3><%= @task.title %></h3>
        <p><%= @task.details %></p>
        <%= link_to "Mark as #{ @task.completed ? 'Not Done' : 'Done' }",
            task_completed_path(@task),
            data: {turbo_method: :patch, turbo_confirm: "Are you sure?"},
            class: "btn btn-success"
        %>
        <a href="<%= task_edit_path(@task) %>" class="btn btn-primary mr-2">Edit</a>
        <%= link_to "Delete",
          task_path(@task),
          data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
          class: "btn btn-danger"
        %>

      </div>
    </div>
  </div>
</div>

app/views/tasks/update.html.erb
<h1> update task </h1>

<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>


<%= link_to 'back to list of tasks', tasks_path %>